name: Preprocessing Notebook Automation

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/preprocessing.ipynb'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/.bashrc
            cd /home/e19452/ml_project
            conda deactivate
            conda activate /home/e19452/ml_project/env
            cd /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts
            # git pull origin main
            jupyter nbconvert --to script /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/notebooks/preprocessing.ipynb --output-dir /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts
            python /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts/preprocessing.py
            # git add /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts/preprocessing.py
            # git commit -m "Automated preprocessing script update"
